name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-check:
    name: Rust Check & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings

      - name: Check compilation
        run: cargo check --workspace --all-targets --all-features

      - name: Run tests
        run: cargo test --workspace --all-features

  wasm-build:
    name: WASM Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build WASM
        run: |
          cd floraison-wasm
          wasm-pack build --target web --out-dir ../floraison-ui/src/lib/wasm --out-name floraison

      - name: Upload WASM artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wasm-build
          path: |
            floraison-ui/src/lib/wasm/*.js
            floraison-ui/src/lib/wasm/*.wasm
            floraison-ui/src/lib/wasm/floraison.d.ts
            floraison-ui/src/lib/wasm/floraison_bg.wasm.d.ts
            floraison-ui/src/lib/wasm/package.json
          retention-days: 1

  ui-check:
    name: UI Check & Test
    runs-on: ubuntu-latest
    needs: wasm-build
    steps:
      - uses: actions/checkout@v4

      - name: Download WASM artifacts
        uses: actions/download-artifact@v4
        with:
          name: wasm-build
          path: floraison-ui/src/lib/wasm/

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('floraison-ui/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        working-directory: floraison-ui
        run: npm ci

      - name: Install Playwright browsers
        working-directory: floraison-ui
        run: npx playwright install --with-deps chromium

      - name: Type check
        working-directory: floraison-ui
        run: npm run check

      - name: Run tests
        working-directory: floraison-ui
        run: npm run test

  build:
    name: Full Build
    runs-on: ubuntu-latest
    needs: [rust-check, wasm-build, ui-check]
    steps:
      - uses: actions/checkout@v4

      - name: Download WASM artifacts
        uses: actions/download-artifact@v4
        with:
          name: wasm-build
          path: floraison-ui/src/lib/wasm/

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('floraison-ui/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install UI dependencies
        working-directory: floraison-ui
        run: npm ci

      - name: Build UI
        working-directory: floraison-ui
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: floraison-ui/build/
          retention-days: 7
