name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-check:
    name: Rust Check & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings

      - name: Check compilation
        run: cargo check --workspace --all-targets --all-features

      - name: Run tests
        run: cargo test --workspace --all-features

  wasm-build:
    name: WASM Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-wasm-${{ hashFiles('**/Cargo.lock') }}

      - name: Build WASM
        run: |
          cd floraison-wasm
          wasm-pack build --target web --out-dir ../floraison-ui/src/lib/wasm --out-name floraison

  ui-check:
    name: UI Check & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: floraison-ui/package-lock.json

      - name: Install dependencies
        run: |
          cd floraison-ui
          npm ci

      - name: Type check
        run: |
          cd floraison-ui
          npm run check

      - name: Lint
        run: |
          cd floraison-ui
          npm run lint

      - name: Run tests
        run: |
          cd floraison-ui
          npm run test

  build:
    name: Full Build
    runs-on: ubuntu-latest
    needs: [rust-check, wasm-build, ui-check]
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install root dependencies
        run: npm install

      - name: Install UI dependencies
        run: |
          cd floraison-ui
          npm ci

      - name: Build WASM
        run: npm run build:wasm

      - name: Build UI
        run: npm run build:ui

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: floraison-ui/build/
